# Generated by Django 4.2.13 on 2024-06-10 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_rename_clientid_encrypteddata_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeys',
            name='Api_key',
        ),
        migrations.AddField(
            model_name='apikeys',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
