# Generated by Django 4.2.13 on 2024-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_encrypteddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypteddata',
            name='key',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
