# Generated by Django 4.2.13 on 2024-06-10 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_rename_api_key_apikeys_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeys',
            name='id',
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='Api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
