# Generated by Django 4.2.13 on 2024-05-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_apikeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='Api_key',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
