# Generated by Django 5.0.6 on 2024-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0002_transaction_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Binance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=1000)),
                ('token_address', models.CharField(max_length=1000)),
            ],
        ),
    ]
