# Generated by Django 5.0.6 on 2024-06-02 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0003_binance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='binance',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta_app.coin_details'),
            preserve_default=False,
        ),
    ]
