# Generated by Django 4.2.13 on 2024-06-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0004_coin_details_binance_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SspWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssp_wallet', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
