# Generated by Django 4.2.13 on 2024-06-04 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0005_sspwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='RePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_pay_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.CharField(max_length=1000)),
                ('un_paid_amount', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
