# Generated by Django 4.2.13 on 2024-06-13 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_remove_apikeys_id_alter_apikeys_api_key'),
        ('meta_app', '0006_repayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=1000)),
                ('payment_datetime', models.CharField(max_length=1000)),
                ('sender_address', models.CharField(max_length=1000)),
                ('receiver_address', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('amount', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.apikeys')),
            ],
        ),
    ]
